name: Deploy Gemini Backend to Lambda

on:
  push:
    branches:
      - main # Or the branch you want to trigger the deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      # - name: Installing Yarn
      #   run: npm install --global yarn

      # - name: Install dependencies
      #   run: yarn install

      - name: Zip Code for Lambda
        run: zip -r function.zip .

      - name: Deploy Lambda Function
        uses: aws-actions/aws-cli-action@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # e.g., us-east-1
          command: |
            aws lambda update-function-code --function-name express --zip-file fileb://function.zip
