name: Deploy Gemini Backend to Lambda

on:
  push:
    branches:
      - main # Or the branch you want to trigger the deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"
          
      - name: Updating and Upgrading packages
        run: |
          sudo apt update -y && sudo apt upgrade -y

      # - name: Installing Yarn
      #   run: npm install --global yarn

      # - name: Install dependencies
      #   run: yarn install

      - name: Zip Code for Lambda
        run: zip -r function.zip .

      - name: Deploy Lambda Function
        run: |
          aws lambda update-function-code --function-name express --zip-file fileb://function.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }} # e.g., us-east-1

